Repository IBM/FfDL, pull requests merged in 2018-07, with the labels that each got.

#107 Remove 4 minute timeout for log follow process
  trainer/trainer/trainer_impl.go
Labels: ffdl-core

#119 Update deprecated framework versions
  docs/user-guide.md
  etc/examples/horovod/manifest_pytorchmnist.yml
  etc/examples/horovod/manifest_tfmnist.yml
  templates/services/learner-configmap.yml
Labels: bug

#120 Update Fashion MNIST example with Seldon-core 0.2
  community/FfDL-Seldon/pytorch-model/README.md
  community/FfDL-Seldon/tf-model/README.md
  demos/fashion-mnist-training/fashion-mnist-webapp/README.md
  demos/fashion-mnist-training/fashion-mnist-webapp/fashion-mnist-webapp.yaml
  demos/fashion-mnist-training/seldon-deployment/fashion-seldon.json
Labels: Dependencies
