Repository IBM/FfDL, pull requests merged in 2018-04, with the labels that each got.

#51 Add developer guide and some customizable features for development build
  README.md
  docs/developer-guide.md
  lcm/service/lcm/constants.go
  lcm/service/lcm/container_helper.go
  lcm/service/lcm/container_helper_extensions.go
  lcm/service/lcm/resources.go
  trainer/trainer/frameworks.go
Labels: enhancement

#35 Minor fix on #273 & #370
  README.md
Labels: docs

#52 Creating CLA
  CLA.md
  CONTRIBUTING.md
Labels: docs

#53 Fix logging bug and clean up on helm chart
  etc/examples/tf-summary-model/gpu-manifest.yml
  etc/examples/tf-summary-model/input_data.py
  etc/examples/tf-summary-model/keys.json
  etc/examples/tf-summary-model/manifest.yml
  etc/examples/tf-summary-model/mnist_with_summaries.py
  etc/examples/tf-summary-model/runtb.sh
  lcm/service/lcm/constants.go
  templates/services/lcm-deployment.yml
  templates/services/restapi-deployment.yml
  templates/services/trainer-deployment.yml
  templates/services/trainingdata-deployment.yml
  templates/services/web-ui.yml
Labels: bug

#63 fix dependencies issue
  Makefile
  README.md
  templates/infrastructure/storage.yml
Labels: Dependencies

#73 Update FfDL UI dependencies and fix Helm issue
  Makefile
  dashboard/Dockerfile
  dashboard/package-lock.json
  dashboard/package.json
  docs/developer-guide.md
Labels: CI/CD, Dependencies
