Repository IBM/FfDL, pull requests merged in 2018-03, with the labels that each got.

#29 Update UI instructions to manually create model zip files
  README.md
  etc/examples/tf-model.zip
Labels: docs

#32 Update helmignore to avoid oversized helm configmap
  .helmignore
Labels: bug

#33 Update UI and font-awesome dependencies.
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/src/assets/font-awesome/HELP-US-OUT.txt
  dashboard/src/assets/font-awesome/css/font-awesome.css
  dashboard/src/assets/font-awesome/css/font-awesome.min.css
  dashboard/src/assets/font-awesome/fonts/FontAwesome.otf
  dashboard/src/assets/font-awesome/fonts/fontawesome-webfont.eot
  dashboard/src/assets/font-awesome/fonts/fontawesome-webfont.svg
  dashboard/src/assets/font-awesome/fonts/fontawesome-webfont.ttf
  dashboard/src/assets/font-awesome/fonts/fontawesome-webfont.woff
  dashboard/src/assets/font-awesome/fonts/fontawesome-webfont.woff2
  dashboard/src/assets/font-awesome/less/animated.less
  dashboard/src/assets/font-awesome/less/bordered-pulled.less
  dashboard/src/assets/font-awesome/less/core.less
  dashboard/src/assets/font-awesome/less/fixed-width.less
  dashboard/src/assets/font-awesome/less/font-awesome.less
  dashboard/src/assets/font-awesome/less/icons.less
  dashboard/src/assets/font-awesome/less/larger.less
  dashboard/src/assets/font-awesome/less/list.less
  dashboard/src/assets/font-awesome/less/mixins.less
  dashboard/src/assets/font-awesome/less/path.less
  dashboard/src/assets/font-awesome/less/rotated-flipped.less
  dashboard/src/assets/font-awesome/less/screen-reader.less
  dashboard/src/assets/font-awesome/less/stacked.less
  dashboard/src/assets/font-awesome/less/variables.less
  dashboard/src/assets/font-awesome/scss/_animated.scss
  dashboard/src/assets/font-awesome/scss/_bordered-pulled.scss
  dashboard/src/assets/font-awesome/scss/_core.scss
  dashboard/src/assets/font-awesome/scss/_fixed-width.scss
  dashboard/src/assets/font-awesome/scss/_icons.scss
  dashboard/src/assets/font-awesome/scss/_larger.scss
  dashboard/src/assets/font-awesome/scss/_list.scss
  dashboard/src/assets/font-awesome/scss/_mixins.scss
  dashboard/src/assets/font-awesome/scss/_path.scss
  dashboard/src/assets/font-awesome/scss/_rotated-flipped.scss
  dashboard/src/assets/font-awesome/scss/_screen-reader.scss
  dashboard/src/assets/font-awesome/scss/_stacked.scss
  dashboard/src/assets/font-awesome/scss/_variables.scss
  dashboard/src/assets/font-awesome/scss/font-awesome.scss
  dashboard/src/index.html
Labels: Dependencies

#37 Adding Contributors in CONTRIBUTING.MD
  CONTRIBUTING.md
  README.md
Labels: docs

#38 Updating maintainers file
  MAINTAINERS.md
Labels: docs

#40 Linkage to watson studio
  README.md
  etc/converter/ffdl-wml.md
  etc/converter/train-deploy-wml.md
  etc/examples/caffe-model/gpu-manifest.yml
  etc/examples/caffe-model/manifest.yml
  templates/services/lcm-deployment.yml
Labels: docs, enhancement

#43 Remove Vagrant reference
  README.md
Labels: docs

#45 Temporary fix for CI with k8s 1.9.4
  Makefile
  README.md
Labels: CI/CD, bug

#47 Update learner entrypoint command to work on k8s 1.9.4 and above
  Makefile
  README.md
  lcm/service/lcm/container_helper_extensions.go
Labels: Dependencies

#50 Removing orphan vagrant references
  README.md
Labels: docs
